name: 京东点点券

on:
    workflow_dispatch:
    schedule:
        - cron: '10 13,17 * * *'
    watch:
        types: [started]
        
jobs:
    build:
        runs-on: ubuntu-latest
        if: github.event.repository.owner.id == github.event.sender.id
        steps:
            - name: Checkout codes
              uses: actions/checkout@v2
            - name: Use Node.js
              uses: actions/setup-node@v2.1.2
              with:
                  node-version: "15.x"
            - name: npm install
              run: |
                  npm install
            - name: "运行【京东点点券】"
              run: |
                  node onlyOneExecute.js
              env:
                  JD_COOKIE: ${{ secrets.JD_COOKIE }}
                  PUSH_KEY: ${{ secrets.PUSH_KEY }}
                  BARK_PUSH: ${{ secrets.BARK_PUSH }}
                  BARK_SOUND: ${{ secrets.BARK_SOUND }}
                  TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
                  TG_USER_ID: ${{ secrets.TG_USER_ID }}
                  DD_BOT_TOKEN: ${{ secrets.DD_BOT_TOKEN }}
                  DD_BOT_SECRET: ${{ secrets.DD_BOT_SECRET }}
                  SYNCURL: https://raw.githubusercontent.com/lxk0301/jd_scripts/master/jd_necklace.js
